# Задание №1

In [1]:
import numpy as np

In [2]:
def nums_np (n):
    a = np.arange(n)
    return a [::-1]
    
    
nums_np (10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание №2

In [3]:
def diag_np (n):
    a = np.diag(np.arange(n))
    print (a)
    return sum(np.diagonal(a))

diag_np (10)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


45

# Задание №3

Дана система линейных уравнений

\begin{equation*}
\LARGE
4*x + 2*y + z = 4 \\
\LARGE
x + 3*y = 12 \\
\LARGE
5*y + 4*z = -3
\end{equation*}

In [4]:
from numpy import linalg
a = np.array(
    [
        [4, 2, 1],
        [1, 3, 0],
        [5, 0, 4]
    ]
)
b = np.array( [4, 12,-3] )
linalg.solve(a,b)

array([-1.56,  4.52,  1.2 ])

In [5]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

# Задача №4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [12]:
""" На сайт заходит очередной посетитель, о покупках которого известно следующее:"""

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [24]:
import matplotlib.pyplot as plt

def cosine_users (a, b):
    bLength = np.linalg.norm( b )
    rez=[]
    for user_id, user_vector in enumerate(a):
        f = [user_vector]
        fLength = np.linalg.norm(f)
        cosine_user = (np.dot(f, b) / (bLength*fLength))
        rez.append([cosine_user, user_id])
    return print(f' ID пользователя имеющего сходство между очередным пользователем среди уже ранее пришедших - {max(rez)[1]} Косинусное сходство {max(rez)[0]}')

cosine_users (users_stats, next_user_stats)

 ID пользователя имеющего сходство между очередным пользователем среди уже ранее пришедших - 7 Косинусное сходство [0.9486833]
